import { Dimensions, Platform, StyleSheet, type ViewStyle } from "react-native";

import { theme } from "./theme";

const { width } = Dimensions.get("window");

function platformShadow(boxShadow: string, nativeShadow: ViewStyle): ViewStyle {
  return Platform.OS === "web" ? ({ boxShadow } as ViewStyle) : nativeShadow;
}

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  flex: { flex: 1 },
  centered: { justifyContent: "center", alignItems: "center" },
  scrollPadding: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 120 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    marginTop: 10,
  },
  backButton: { width: 40, height: 40, justifyContent: "center" },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatarContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  brandText: { fontSize: 22, color: theme.colors.textMain },
  notificationBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  notificationDot: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.accentRed,
    borderWidth: 2,
    borderColor: theme.colors.surface,
  },
  welcomeText: { fontSize: 16, color: theme.colors.textSecondary, marginBottom: 24 },
  balanceCard: {
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    ...platformShadow(`0 10px 15px ${theme.colors.secondary}33`, {
      shadowColor: theme.colors.secondary,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 15,
    }),
    elevation: 8,
  },
  balanceHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  labelCaps: { fontSize: 10, letterSpacing: 1.5 },
  balanceContent: {},
  balanceValue: { fontSize: 32, color: "#FFF", marginBottom: 12 },
  usdcPill: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  usdcPillText: { color: "#FFF", fontSize: 14 },
  liveText: { color: theme.colors.accentGreen, fontSize: 10 },
  homeActionGrid: { flexDirection: "row", gap: 16, marginBottom: 32 },
  scanBtn: {
    flex: 1.5,
    backgroundColor: theme.colors.primary,
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  scanIconBox: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  scanBtnText: { color: "#FFF", fontSize: 18 },
  rightActionColumn: { flex: 1, gap: 16 },
  smallActionBtn: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  smallActionText: { color: theme.colors.textMain, fontSize: 14, marginTop: 8 },
  tipsCard: {
    flexDirection: "row",
    backgroundColor: theme.colors.surface,
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: "center",
    gap: 16,
  },
  tipsIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "rgba(74, 222, 128, 0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  tipsContent: { flex: 1 },
  tipsTitle: { fontSize: 16, color: theme.colors.textMain, marginBottom: 4 },
  tipsSub: { fontSize: 13, color: theme.colors.textSecondary, lineHeight: 18 },
  visaCard: {
    height: 210,
    borderRadius: 24,
    padding: 24,
    justifyContent: "space-between",
    marginBottom: 20,
  },
  cardTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  visaText: { color: "#FFF", fontSize: 20, fontStyle: "italic" },
  cardChip: { width: 45, height: 35, backgroundColor: "#FFD700", borderRadius: 8, opacity: 0.8 },
  cardNumber: { color: "#FFF", fontSize: 22, letterSpacing: 2 },
  cardDetailsRow: { flexDirection: "row", justifyContent: "space-between" },
  cardLabel: { color: "rgba(255,255,255,0.6)", fontSize: 8, marginBottom: 4 },
  cardValue: { color: "#FFF", fontSize: 14 },
  useDifferentBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(255, 112, 8, 0.05)",
    padding: 16,
    borderRadius: 16,
    marginBottom: 32,
  },
  useDifferentText: { color: theme.colors.primary, fontSize: 14 },
  depositSection: {
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  labelSmall: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    letterSpacing: 1,
    marginBottom: 16,
  },
  amountInputBox: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    paddingBottom: 16,
    marginBottom: 24,
  },
  currencySymbol: { fontSize: 32, color: theme.colors.primary, marginRight: 8 },
  mainAmountInput: { fontSize: 48, color: theme.colors.textMain, flex: 1 },
  quickAmountRow: { flexDirection: "row", gap: 12, marginBottom: 32 },
  quickAmountBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  quickAmountBtnActive: {
    backgroundColor: "rgba(255, 112, 8, 0.1)",
    borderColor: theme.colors.primary,
  },
  quickAmountText: { fontSize: 16, color: theme.colors.textMain, fontWeight: "700" },
  quickAmountTextActive: { color: theme.colors.primary },
  confirmDepositBtn: {
    backgroundColor: theme.colors.primary,
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmDepositText: { color: "#FFF", fontSize: 16 },
  infoBox: { flexDirection: "row", gap: 16, marginTop: 24, padding: 16 },
  infoIconBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  infoTitle: { fontSize: 14, color: theme.colors.textMain, marginBottom: 4 },
  infoSub: { fontSize: 12, color: theme.colors.textSecondary, lineHeight: 18 },
  pageTitle: { fontSize: 28, color: theme.colors.textMain, marginBottom: 8 },
  pageSub: { fontSize: 14, color: theme.colors.textSecondary, marginBottom: 24 },
  historyTabs: {
    flexDirection: "row",
    backgroundColor: theme.colors.surface,
    padding: 4,
    borderRadius: 12,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  historyTab: {
    flex: 1,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  historyTabActive: {
    backgroundColor: theme.colors.background,
    ...platformShadow("0 2px 4px rgba(0, 0, 0, 0.1)", {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    }),
    elevation: 2,
  },
  historyTabText: { fontSize: 14, color: theme.colors.textSecondary },
  historyTabTextActive: { color: theme.colors.textMain, fontWeight: "700" },
  dateHeader: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    letterSpacing: 1,
    marginBottom: 16,
  },
  promoCard: { borderRadius: 24, padding: 24, marginTop: 32, overflow: "hidden" },
  promoContent: { flex: 1, zIndex: 1 },
  promoTitle: { fontSize: 20, color: "#FFF", marginBottom: 12 },
  promoSub: { fontSize: 14, color: "rgba(255,255,255,0.8)", lineHeight: 20 },
  promoIcon: { position: "absolute", right: -10, bottom: -10, opacity: 0.2 },
  sendBalanceSection: { alignItems: "center", marginVertical: 32 },
  kesBalanceRow: { flexDirection: "row", alignItems: "baseline" },
  kesPrefix: { fontSize: 24, color: theme.colors.primary },
  kesAmount: { fontSize: 36, color: theme.colors.textMain },
  percentBadge: {
    backgroundColor: "rgba(74, 222, 128, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginTop: 12,
  },
  percentText: { color: theme.colors.accentGreen, fontSize: 12 },
  serviceGrid: { flexDirection: "row", flexWrap: "wrap", gap: 16, justifyContent: "space-between" },
  serviceCard: {
    width: (width - 56) / 2,
    backgroundColor: theme.colors.surface,
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  serviceIconBox: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: theme.colors.surfaceLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  serviceLabel: { color: theme.colors.textMain, fontSize: 15, fontWeight: "700", marginBottom: 4 },
  serviceSub: { color: theme.colors.textSecondary, fontSize: 11 },
  payeeRow: { flexDirection: "row", gap: 12, marginTop: 16 },
  payeeAvatarContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: theme.colors.primary,
    padding: 2,
  },
  payeeAvatar: {
    flex: 1,
    backgroundColor: theme.colors.surfaceLight,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  actionGrid: { flexDirection: "row", justifyContent: "space-between", marginTop: 32 },
  actionItem: { alignItems: "center", flex: 1 },
  actionIconBox: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  actionLabel: { fontSize: 12, color: theme.colors.textMain },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 32,
    marginBottom: 16,
  },
  sectionTitle: { fontSize: 18, color: theme.colors.textMain },
  viewAll: { fontSize: 12, color: theme.colors.primary, textTransform: "uppercase" },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    padding: 16,
    borderRadius: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  listIconBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  listTitle: { fontSize: 16, color: theme.colors.textMain, marginBottom: 4 },
  listSub: { fontSize: 12, color: theme.colors.textSecondary },
  listAmount: { fontSize: 16, fontWeight: "700", marginBottom: 4 },
  categoryBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: theme.colors.background,
  },
  categoryText: { fontSize: 10, color: theme.colors.textSecondary },
  profileHeader: { alignItems: "center", marginVertical: 32 },
  profileAvatarLarge: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    borderWidth: 4,
    borderColor: theme.colors.primary,
  },
  profileAvatarTextLarge: { fontSize: 36, color: theme.colors.primary },
  profileName: { fontSize: 24, color: theme.colors.textMain, marginBottom: 4 },
  profileEmail: { fontSize: 14, color: theme.colors.textSecondary, marginBottom: 16 },
  tierBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 112, 8, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
  },
  tierText: { color: theme.colors.primary, fontSize: 12 },
  walletAddressContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    padding: 20,
    borderRadius: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  addressText: { color: theme.colors.textMain, fontSize: 16 },
  copyButton: { padding: 8, backgroundColor: theme.colors.background, borderRadius: 12 },
  menuGroup: { gap: 12, marginBottom: 32 },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    padding: 18,
    borderRadius: 20,
    gap: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  menuIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  menuLabel: { flex: 1, color: theme.colors.textMain, fontSize: 15 },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 18,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.2)",
    backgroundColor: theme.colors.surface,
  },
  logoutText: { color: theme.colors.accentRed, fontSize: 16 },
  versionText: {
    textAlign: "center",
    color: theme.colors.textSecondary,
    fontSize: 12,
    marginTop: 24,
  },
  formContainer: { marginTop: 20 },
  label: { fontSize: 14, color: theme.colors.textSecondary, marginBottom: 12 },
  inputBox: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 60,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
    flexDirection: "row",
    alignItems: "center",
  },
  formInput: { fontSize: 18, color: theme.colors.textMain },
  primaryButton: {
    backgroundColor: theme.colors.primary,
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
  },
  primaryButtonText: { color: "#FFF", fontSize: 16, fontWeight: "700" },
  buttonDisabled: { opacity: 0.5 },
  successTitle: { fontSize: 24, color: theme.colors.textMain, marginBottom: 8 },
  successSub: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  conversionBox: {
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 20,
    marginTop: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  conversionHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 },
  conversionHeaderText: { color: theme.colors.primary, fontSize: 10, letterSpacing: 1 },
  conversionRateText: { color: theme.colors.textMain, fontSize: 20, marginBottom: 4 },
  conversionSub: { color: theme.colors.textSecondary, fontSize: 11 },
  summaryCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    padding: 24,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  summaryLabel: {
    color: theme.colors.textSecondary,
    fontSize: 10,
    letterSpacing: 1,
    marginBottom: 12,
  },
  summaryValue: { color: theme.colors.textMain, fontSize: 32, marginBottom: 20 },
  divider: { height: 1, backgroundColor: theme.colors.border, marginBottom: 20 },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 12 },
  summaryRowLabel: { color: theme.colors.textSecondary, fontSize: 14 },
  summaryRowValue: { color: theme.colors.textMain, fontSize: 14, fontWeight: "700" },
  buttonRow: { flexDirection: "row", alignItems: "center" },
  secondaryButton: {
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
  },
  secondaryButtonText: { color: theme.colors.textMain, fontSize: 14 },
  bottomNav: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    height: 80,
    backgroundColor: theme.colors.surface,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...platformShadow("0 5px 10px rgba(0, 0, 0, 0.1)", {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
    }),
    elevation: 5,
  },
  tabButton: { flex: 1, alignItems: "center", justifyContent: "center" },
  tabIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  tabIconContainerActive: { backgroundColor: theme.colors.primary },
  tabLabel: { fontSize: 10, color: theme.colors.textSecondary },
  quickServicesGrid: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  quickServiceItem: { alignItems: "center", width: (width - 40) / 4 },
  quickServiceIconBox: {
    width: 50,
    height: 50,
    borderRadius: 15,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  quickServiceLabel: { fontSize: 11, color: theme.colors.textMain },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: theme.colors.surface,
    borderRadius: 32,
    padding: 32,
    width: "100%",
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  modalIconBg: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: theme.colors.accentGreen,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  modalTitle: { fontSize: 22, color: theme.colors.textMain, marginBottom: 12, textAlign: "center" },
  modalSub: {
    fontSize: 15,
    color: theme.colors.textSecondary,
    textAlign: "center",
    marginBottom: 32,
  },
  modalCloseBtn: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 40,
    paddingVertical: 14,
    borderRadius: 16,
    width: "100%",
    alignItems: "center",
  },
  modalCloseText: { color: "#FFF", fontSize: 16 },
});
